### ISSUE TITLE
Default unit

### ISSUE THREAD

**Issue by andrewMacmurray** [andrewMacmurray/elm-delay#8]
Curious if anyone is using a mixture of `TimeUnit`s? Was thinking about changing the api to have a default unit of milliseconds so it's a little cleaner:

```elm
Delay.after 500 SomethingTriggered
```

```elm
Delay.sequence
    [ ( 100, MsgOne )
    , ( 200, MsgTwo )
    , ( 100, MsgThree )
    ]
```

And maybe add some helpers to convert millis to other time units:

```elm
Delay.after (Delay.seconds 5) SomethingTriggered
```

```elm
seconds : Millis -> Millis
seconds millis =
    1000 * millis
```

@lenards given you've been using this recently do you have any thoughts?

**Comment by alenards** [comment]
I have tended to use only one `TimeUnit` and that's usually milliseconds. 

I do like the idea of the `Delay.seconds` so it's clear at the "call site" what units are being used. 

I would be down to take a crack at doing the helpers if you'd like.

**Comment by andrewMacmurray** [comment]
That's good to know, thanks @alenards. I was planning on doing the cleanups this weekend but would be good to get some feedback / review from you if that's cool?

**Comment by lenards** [comment]
DEFINITELY!! I would love to get look over changes and offer any
thoughts/notes.
